config/routes.rb
Rails.application.routes.draw do
  resources :movements
  resources :bills
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'bills#index'
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :bill
  belongs_to :user

  paginates_per 50

  validates :description, :date, :time, :amount, presence: true


  # def positive_value
  #   if self.amount > 0
  #   else
  #     puts "*** El monto del movimiento debe ser positivo, al seleccionar debito se restara de la cuenta por mas de que ingrese un numero positivo *** "
  #     errors.add(:amount, 'El monto debe ser positivo')
  #     break
  #   end
  # end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  load_and_authorize_resource
  before_action :set_movement, only: %i[ show edit update destroy ]

  # GET /movements or /movements.json
  def index
    @movements = Movement.order(:movement_type).page params[:page]
    @movements = @movements.where(date: params[:date]) unless params[:date].blank?
    @movements = @movements.where(:bill_id => params[:bill_id]) if params[:bill_id]
    @movements = @movements.joins(:bill).where('bill.bill_type' => params[:filter]).all unless params[:filter].blank?
    @movements = @movements.order((params[:by] || "date") + " " + (params[:order] || "asc"))
  end

  # GET /movements/1 or /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements or /movements.json
  def create
    @movement = Movement.new(movement_params)
    @bill = Bill.find(@movement.bill_id)
    @movement.user_id = current_user.id


    if @movement.date.nil? || @movement.date > @movement.bill.end_time || @movement.date < @movement.bill.begin_date
      redirect_to movements_path, notice: "El movimiento no se realizo. La fecha es invalida."
    else
      if @movement.movement_type == 'C'
        respond_to do |format|
          if @movement.save
            format.html { redirect_to movement_url(@movement), notice: "Movement was successfully created." }
            format.json { render :show, status: :created, location: @movement }
            @movement.total_amount = @bill.balance + @movement.amount
            @movement.save
            @bill.balance = @bill.balance + @movement.amount
            @bill.save
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @movement.errors, status: :unprocessable_entity }
          end
        end
      elsif @movement.movement_type == 'D'
        if @movement.amount > @movement.bill.balance
          redirect_to movements_path, notice: "El movimiento no se realizo. El monto es mayor que el balance."
        else
          respond_to do |format|
            if @movement.save
              format.html { redirect_to movement_url(@movement), notice: "Movement was successfully created." }
              format.json { render :show, status: :created, location: @movement }
              @movement.total_amount = @bill.balance - @movement.amount
              @movement.save
              @bill.balance = @bill.balance - @movement.amount
              @bill.save
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @movement.errors, status: :unprocessable_entity }
            end
          end
        end
      end
    end
  end

  # PATCH/PUT /movements/1 or /movements/1.json
  def update
    if @movement.movement_type == 'C'
      respond_to do |format|
        if @movement.update(movement_params)
          format.html { redirect_to movement_url(@movement), notice: "Movement was successfully updated." }
          format.json { render :show, status: :ok, location: @movement }
          @bill = Bill.find(@movement.bill_id)
          @bill.balance = @bill.balance - @movement.amount
          @bill.save
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @movement.errors, status: :unprocessable_entity }
        end
      end
    elsif @movement.movement_type == 'D'
      if @movement.amount > @movement.bill.balance
        redirect_to movements_path, notice: "El movimiento no se realizo. El monto es mayor que el balance."
      else
        respond_to do |format|
          if @movement.update(movement_params)
            format.html { redirect_to movement_url(@movement), notice: "Movement was successfully updated." }
            format.json { render :show, status: :ok, location: @movement }
            @bill = Bill.find(@movement.bill_id)
            @bill.balance = @bill.balance - @movement.amount
            @bill.save
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @movement.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # DELETE /movements/1 or /movements/1.json
  def destroy
    @movement.destroy
    if @movement.movement_type == 'C'
      if @movement.amount > @movement.bill.balance
        redirect_to movements_path, notice: "El movimiento no se realizo. El monto es mayor que el balance."
      else
        respond_to do |format|
          format.html { redirect_to movements_url, notice: "Movement was successfully destroyed." }
          format.json { head :no_content }
          @bill = Bill.find(@movement.bill_id)
          @bill.balance = @bill.balance - @movement.amount
          @bill.save
        end
      end
    elsif @movement.movement_type == 'D'
      respond_to do |format|
        format.html { redirect_to movements_url, notice: "Movement was successfully destroyed." }
        format.json { head :no_content }
        @bill = Bill.find(@movement.bill_id)
        @bill.balance = @bill.balance + @movement.amount
        @bill.save
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movement_params
      params.require(:movement).permit(:movement_type, :date, :time, :amount, :description, :bill_id, :user_id, :total_amount)
    end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.erb
<%= form_with(model: movement) do |form| %>
  <% if movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
        <% movement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row justify-content-center container-gray" style="padding: 1% 0%;">
    <div class="field">
      <%= form.label :movement_type %>
      <select name="movement[movement_type]" class="form-field">
        <option value="C">Ingreso (Credito)</option>
        <option value="D">Gasto (Debito)</option>
      </select>
    </div>

    <div class="field">
      <%= form.label :date %>
      <input type="date" name="movement[date]" value="<%= movement.date %>" max="<%=DateTime.current.to_date%>" class="form-field" />
    </div>

    <div class="field">
      <%= form.label :time %>
      <%= form.time_select :time, class: 'form-field' %>
    </div>

    <div class="field">
      <%= form.label :amount %>
      <%#= form.number_field :amount %>
      <input class="form-field" name="movement[amount]" type="number" min="0">
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :bill_id %>
      <%= form.collection_select(:bill_id, Bill.where(user_id: current_user.id), :id, :bill_type, {}, {:class => 'form-field'})  %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-sm button-gray' %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Show', @movement, class: 'btn btn-sm button-gray' %>
<%= link_to 'Back', movements_path, class: 'btn btn-sm button-gray' %>

app/views/movements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movements</h1>

<form method="GET" action="/movements" class="filterborders" style="width: 520px">
  <strong>Date:</strong> <input type="date" name="date" max="<%=DateTime.current.to_date%>" class="filter-field"/>
  <strong>Cuenta:</strong> <input type="text" name="filter" class="filter-field"/>
  <input type="submit" class="btn btn-sm button-white"/>
</form>

<br>

<table class="table table-secondary">
  <thead>
    <tr>
      <th><%= link_to "Movement type", movements_path(:sort => true, :by => "movement_type", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Date", movements_path(:sort => true, :by => "date", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Time", movements_path(:sort => true, :by => "time", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Credito", movements_path(:sort => true, :by => "amount", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Debito", movements_path(:sort => true, :by => "amount", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Description", movements_path(:sort => true, :by => "description", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Bill", movements_path(:sort => true, :by => "bill_id", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Saldo", movements_path(:sort => true, :by => "total_amount", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
        <% if can? :manage, movement  %>
        <% if movement.movement_type == "C"%>
          <td>Crédito</td>
        <% else %>
          <td>Débito</td>
        <% end %>
          <td><%= movement.date %></td>
          <td><%= movement.time %></td>
          <% if movement.movement_type == "C" %>
            <td><%= movement.amount %></td>
            <td>0</td>
          <% else %>
            <td>0</td>
            <td><%= movement.amount %></td>
          <% end %>
          <td><%= movement.description %></td>
          <td><%= movement.bill.bill_type %></td>
          <td><%= movement.total_amount %></td>
          <td><%= link_to 'Show', movement %></td>
          <!-- <td><%#= link_to 'Edit', edit_movement_path(movement) %></td> -->
          <td><%= link_to 'Destroy', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @movements %>

<br>

<%= link_to 'New Movement', new_movement_path, class: 'btn btn-sm button-gray' %>

app/views/movements/new.html.erb
<h1>New Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Back', movements_path, class: 'btn btn-sm button-gray' %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container-gray" style="width: 300px;">
  <p>
    <strong>Movement type:</strong>
    <%= @movement.movement_type %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @movement.date %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= @movement.time %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= @movement.amount %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @movement.description %>
  </p>

  <p>
    <strong>Bill:</strong>
    <%= @movement.bill.bill_type %>
  </p>

  <p>
    <strong>Saldo:</strong>
    <%= @movement.total_amount %>
  </p>
</div>

<%= link_to 'Edit', edit_movement_path(@movement), class: 'btn btn-sm button-gray' %>
<%= link_to 'Back', movements_path, class: 'btn btn-sm button-gray' %>