config/routes.rb
Rails.application.routes.draw do
  resources :movements
  resources :bills
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'bills#index'
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :movements
  belongs_to :user

  validates :bill_type, :balance, presence: true

  paginates_per 50

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  load_and_authorize_resource
  before_action :set_bill, only: %i[ show edit update destroy ]

  # GET /bills or /bills.json
  def index
    @bills = Bill.order(:bill_type).page params[:page]
  end

  # GET /bills/1 or /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)
    @bill.user_id = current_user.id
    respond_to do |format|
      if @bill.save
        format.html { redirect_to bill_url(@bill), notice: "Bill was successfully created." }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bill_url(@bill), notice: "Bill was successfully updated." }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:bill_type, :begin_date, :end_time, :balance, :user_id)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_with(model: bill) do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
        <% bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row justify-content-center container-gray" style="padding: 1% 0%;">
    <div class="form-div">
      <%= form.label :bill_type %>
      <%= form.text_field :bill_type, class: 'form-field' %>
    </div>

    <div class="form-div">
      <%= form.label :begin_date %>
      <input type="date" name="bill[begin_date]" value="<%= bill.begin_date %>" class="form-field" />
    </div>

    <div class="form-div">
      <%= form.label :end_time %>
      <input type="date" name="bill[end_time]" value="<%= bill.end_time %>" class="form-field" />
    </div>

    <div class="form-div">
      <%= form.label :balance %>
      <%#= form.text_field :balance %>
      <input name="bill[balance]" value="<%= bill.balance %>" type="number" min="0" class="form-field">
    </div>
  </div>
  <br>

  <div class="actions">
    <%= form.submit class: 'btn btn-sm button-gray' %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill, class: 'btn btn-sm button-gray' %>
<%= link_to 'Back', bills_path, class: 'btn btn-sm button-gray' %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table class="table table-secondary">
  <thead>
    <tr>
      <th>Bill type</th>
      <th>Begin date</th>
      <th>End time</th>
      <th>Balance</th>
      <th>Movements</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <% if can? :manage, bill  %>
          <td><%= bill.bill_type %></td>
          <td><%= bill.begin_date %></td>
          <td><%= bill.end_time %></td>
          <td><%= bill.balance %></td>
          <td><%= link_to bill.movements.count, movements_path(:bill_id => bill.id) %></td>
          <td><%= link_to 'Show', bill %></td>
          <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
          <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @bills %>

<br>

<%= link_to 'New Bill', new_bill_path, class: 'btn btn-sm button-gray' %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Back', bills_path, class: 'btn btn-sm button-gray' %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-gray" style="width: 300px;">
  <p>
    <strong>Bill type:</strong>
    <%= @bill.bill_type %>
  </p>

  <p>
    <strong>Begin date:</strong>
    <%= @bill.begin_date %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= @bill.end_time %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= @bill.balance %>
  </p>
</div>


<%= link_to 'Edit', edit_bill_path(@bill), class: 'btn btn-sm button-gray' %>
<%= link_to 'Back', bills_path, class: 'btn btn-sm button-gray' %>